Enable send message to specific queue Time-to-live
UnionVMS/UVMS-UVMSCommonsLibrary pull request #68
Opened 2018-06-22 08:51 UTC by ksschockaert

Enable message Time-to-live for the abstract message producer sendMessageToSpecificQueue method.
The purpose of this change is to provide Time-to-live functionality on sending request messages that are  part of a blocking timeout message consumer flow. This would prevent these request messages from unecessary piling up in the rare case a receiving module would be down.

2018-06-22 18:15 UTC, gregoryrinaldi requested changes
Seems duplicated to me you can call the method with same signature and put a default timer perhaps?
someting like

public String sendMessageToSpecificQueue(String messageToSend, Destination destination, Destination replyTo, long timeToLiveInMillis) throws MessageException {
return sendMessageToSpecificQueue(messageToSend, destination, replyTo, "10000")
}

2018-06-25 11:00 UTC, ebrygg commented
I do think that using timeouts actually camouflages the underlying problem of the lacking resend/error handling, I see no problem with the implementation but handle with care

2018-06-25 11:02 UTC, ebrygg submitted a review, later dismissed
Ok but please consider using a different approach to handle these kind of scenarios

2018-06-28 14:51 UTC, stainii commented
Thanks Greg. Instead of "1000", I've used the default value, so that the code behaves exactly the same as before.

Andreas, I agree. This does, indeed, not remove the need of proper error handling.
We would like to specify timeout to JMS messages to do fine-tuning in cases where JMS messages don't need guaranteed delivery. I actually expect this functionality to be rarely used, once we stop doing "synchronous" requests over JMS and go for REST instead.

2018-06-28 14:53 UTC, stainii commented
test me

2018-06-28 14:55 UTC, stainii commented
test me

2018-06-28 15:42 UTC, stainii commented
Test me

2018-07-02 13:30 UTC, gregoryrinaldi approved these changes

2018-07-02 13:31 UTC, merged